[2021-09-27 15:00:02,853] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-27T14:50:00+00:00 [queued]>
[2021-09-27 15:00:02,890] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-27T14:50:00+00:00 [queued]>
[2021-09-27 15:00:02,893] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 15:00:02,894] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-09-27 15:00:02,896] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 15:00:02,934] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): say_hello> on 2021-09-27T14:50:00+00:00
[2021-09-27 15:00:02,958] {standard_task_runner.py:52} INFO - Started process 14900 to run task
[2021-09-27 15:00:02,970] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'say_hello', '2021-09-27T14:50:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp83eyt8u0', '--error-file', '/tmp/tmppimjbrrb']
[2021-09-27 15:00:02,996] {standard_task_runner.py:77} INFO - Job 9: Subtask say_hello
[2021-09-27 15:00:03,109] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.say_hello 2021-09-27T14:50:00+00:00 [running]> on host 4e8a4ded565b
[2021-09-27 15:00:03,925] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nadanai
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=say_hello
AIRFLOW_CTX_EXECUTION_DATE=2021-09-27T14:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-27T14:50:00+00:00
[2021-09-27 15:00:03,941] {my_dag.py:10} INFO - Hello, SAKSIAM!!
[2021-09-27 15:00:03,942] {python.py:151} INFO - Done. Returned value was: None
[2021-09-27 15:00:04,086] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=say_hello, execution_date=20210927T145000, start_date=20210927T150002, end_date=20210927T150004
[2021-09-27 15:00:04,404] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-27 15:00:04,782] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
